### ISSUE TITLE
Dynamicly strip client field

### ISSUE THREAD

**Issue by runningman84** [sensu-extensions/sensu-extensions-influxdb#11]
My metrics check looks like this:
```
metrics-load.rb --scheme :::scheme_prefix::::::name:::.load'
```
The scheme_prefix is a client field like "prod.sensu.aws.eu-central-1."

It can be stripped with this function:
```
key.gsub!(event[:client][:scheme_prefix], '')
```
Can this function be integrated into your extension? This would allow us to use the official extension instead of my private fork.

**Comment by stevenviola** [comment]
Hey @runningman84. Are you trying to just remove some of the hostname, in this case `prod.sensu.aws.eu-central-1.` or the entire hostname? Have you checked out the [templates feature](https://github.com/sensu-extensions/sensu-extensions-influxdb#config-attributes) in this extension? I think either using the templates or the `strip_metric` can accomplish what you're trying to do. If you need help with the templates, @luisdavim should be able to help you.

If you could post some of the Graphite formatted output from your plugins, and how you want the InfluxDB insert to look like, that would help.

Thanks

**Comment by runningman84** [comment]
My complete key looks like this:
prod.sensu.aws.eu-central-1.server1.loadavg.one
The first part is the dynamic prefix
prod.sensu.aws.eu-central-1.
The middle part is the hostname:
server1
The last part is the metric:
Load... 

The prefix can be changed in the environment, chef role and other places. I do not have complete control of it. But in every case the prefix is stored as the client attribute. 

Is is possible to strip this dynamic part with templates?

**Comment by stevenviola** [comment]
Here's the[ relevant section of the extension](https://github.com/sensu-extensions/sensu-extensions-influxdb/blob/8f1d024f9171d9aab40d29264885073b59ef26d4/lib/sensu/extensions/influxdb.rb#L117-L124) where `strip_metric` is executed. It looks like that does the same gsub you want to do.

If the prefix is stored as the client attribute in the sensu event, then setting `strip_metric` to `host` will remove the hostname (what's stored in the client attribute) from the metric. If you don't want to remove the client attribute, then you can set `strip_metric` to a constant string in your config file on the sensu-server which is running the extension, or you can define `strip_metric` on a check by check basis by defining it in the check definition in an influxdb dict. It's loaded in this extension from `event[:check][:influxdb][:strip_metric]`.

If I understand correctly, it seems like you'll want to take your current `scheme_prefix` and format it in your check like so:

```
{
  "checks": {
    "metrics-load": {
      "command": "metrics-load.rb --scheme :::scheme_prefix::::::name:::.load",
      "handlers": [
        "metrics"
      ],
      "interval": 10,
      "type": "metric",
      "influxdb": {
        "strip_metric": :::scheme_prefix:::
      }
    }
  }
}
``` 
Alternatively, you could change the command to not start with the `scheme_prefix`, and instead use the client attribute:

```
"command": "metrics-load.rb --scheme :::client:::.load",
```

And then on the sensu-server, have your config file look something like this:

```
{
  "influxdb": {
    "database": "metrics",
    "host": <host>,
    "port": <port>,
    "use_ssl": false,
    "strip_metric": "host",
  }
}
```

**Comment by runningman84** [comment]
Is it also possible to strip the scheme_prefix and the client name?

I do not really need these values because I can configure them using tags...

**Comment by luisdavim** [comment]
@runningman84 you can use the templates feature, has @stevenviola mentioned, there's a special keyword `nil` that you can use to ignore some of the fields.
