### ISSUE TITLE
Templates has no guaranteed order

### ISSUE THREAD

**Issue by zemmet** [sensu-extensions/sensu-extensions-influxdb#12]
When using multiple templates one cannot rely on the order of templates in the definition. and Hence templates can randomly match patterns. i.e. in case we have templates like:
`"templates": {
"foo\\.bar\\..*": "measurement.field*",
".*": "measurement.tag1.field"
}`
The key `foo.bar.foobar` will be rendered with field name either `foobar` or `bar.foobar` following the template parsing, and so we cannot rely on the latter one as fall back rule. 
If the matches are exclusive there is no problem.

The right way of defining template rules, I believe, would be using array of hashes instead:
`"templates": [
{"foo\\.bar\\..*": "measurement.field*"},
{".*": "measurement.tag1.field"}
]`

I'm submitting it as an issue as the README says:
> You can specifty multiple templates, if your metric matches more than one the first one will be used.

**Comment by luisdavim** [comment]
PR #13 should fix this, you can now define your templates using an array of hashes.
