### ISSUE TITLE
Is anyone taking care of this repo?

### ISSUE THREAD

**Issue by luisdavim** [sensu-extensions/sensu-extensions-influxdb#3]
Hi,

Is anyone looking at PRs?

Luis

**Comment by mbbroberg** [comment]
Following up on what I wrote in #2, we're working on a better visibility now. Would you be able to help as a maintainer?

**Comment by luisdavim** [comment]
Sure, I'd be happy to help. 
I can do code reviews for both plugins and extensions...

**Comment by mbbroberg** [comment]
Awesome @luisdavim! Let's talk - shoot me an email to matt /at/ sensu.io and we can discuss more. And thank you! 

Closing this issue as resolved.
